version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 1200
      runas: root