version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 1200
      runas: ec2-user